### ISSUE TITLE
[IMPROVEMENT] Make Images Bigger

### ISSUE THREAD

**Issue by brunocalado** [Syrious/foundryvtt-journal-font-scaler#1]
**Is your feature request related to a problem? Please describe.**
I use some handouts with small text. It would be nice to be able to increase the size of it too.
![image](https://github.com/user-attachments/assets/ec83c7cd-14ba-492a-808a-19aec6a4ce00)

**Comment by Syrious** [comment]
Hey there,

just for my understanding: This handout is an image and you want to resize/scale images in general?

**Comment by Syrious** [comment]
Try out version 0.1.0. I added image scaling. I also updated the readme file to clarify its usage :)
